import Head from "next/head";
import moment from "moment";
import { prisma } from "../lib/prisma";
import type { Post } from "@prisma/client";
import type { GetStaticProps } from "next";

type Props = {
  posts: Post[];
};

export default function Home({ posts }: Props) {
  return (
    <>
      <Head>
        <title>AI Blog</title>
        <meta name="description" content="Blog generated by ai" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-2xl pt-12">
        <h1 className="text-4xl font-bold">Blog</h1>
        <p className="pt-4 text-gray-400">
          This blog is generated from AI using Elon's tweets.
        </p>
        <div className="pt-8">
          {posts.map((post) => (
            <>
              <div className="flex justify-between">
                <h2 className="text-xl font-semibold max-w-lg">{post.title}</h2>
                <div className="text-gray-400">
                  {moment(post.createdAt).format("MMM Do YY")}
                </div>
              </div>
            </>
          ))}
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await prisma.post.findMany();

  return {
    props: { posts: JSON.parse(JSON.stringify(posts)) },
    revalidate: 86400,
  };
};
