import moment from "moment";
import parse from "html-react-parser";
import { getPost } from "../../../lib";

type Props = {
  params: { id: string };
};

export default async function Post({ params }: Props) {
  const post = await getPost(Number(params.id));
  return (
    <>
      <h1 className="sm:text-5xl text-4xl font-bold">{post?.title}</h1>
      <h2 className="pt-4 text-gray-400">
        {moment(post?.createdAt).format("MMMM DD, YYYY")}
      </h2>
      <article className="py-10 prose prose-invert prose-h1:text-2xl">
        {parse(post?.content as string)}
      </article>
      <hr className="border-gray-600 pb-8" />
      <a className="italic pb-8 text-gray-300" href={post.tweetUrl}>
        Generated by AI using{" "}
        <span className="text-blue-300 hover:text-blue-400 underline">
          Elon's tweet
        </span>
      </a>
    </>
  );
}
